from pathlib import Path
id=1401
slug='circle-and-rectangle-overlapping'
y,m='2026','04'
post=Path(f'posts/leetcode/{y}/{m}/leetcode-{id}-{slug}.html')
img=Path(f'assets/img/leetcode/{y}/{m}/leetcode-{id}-20260430.svg')
post.parent.mkdir(parents=True,exist_ok=True); img.parent.mkdir(parents=True,exist_ok=True)
code_java='''class Solution {\n    public boolean checkOverlap(int radius, int xCenter, int yCenter, int x1, int y1, int x2, int y2) {\n        int cx = Math.max(x1, Math.min(xCenter, x2));\n        int cy = Math.max(y1, Math.min(yCenter, y2));\n        long dx = xCenter - cx;\n        long dy = yCenter - cy;\n        return dx * dx + dy * dy <= 1L * radius * radius;\n    }\n}'''
code_go='''func checkOverlap(radius int, xCenter int, yCenter int, x1 int, y1 int, x2 int, y2 int) bool {\n    cx := max(x1, min(xCenter, x2))\n    cy := max(y1, min(yCenter, y2))\n    dx := xCenter - cx\n    dy := yCenter - cy\n    return dx*dx+dy*dy <= radius*radius\n}\n\nfunc min(a, b int) int { if a < b { return a }; return b }\nfunc max(a, b int) int { if a > b { return a }; return b }'''
code_cpp='''class Solution {\npublic:\n    bool checkOverlap(int radius, int xCenter, int yCenter, int x1, int y1, int x2, int y2) {\n        int cx = max(x1, min(xCenter, x2));\n        int cy = max(y1, min(yCenter, y2));\n        long long dx = xCenter - cx;\n        long long dy = yCenter - cy;\n        return dx * dx + dy * dy <= 1LL * radius * radius;\n    }\n};'''
code_py='''class Solution:\n    def checkOverlap(self, radius: int, xCenter: int, yCenter: int, x1: int, y1: int, x2: int, y2: int) -> bool:\n        cx = max(x1, min(xCenter, x2))\n        cy = max(y1, min(yCenter, y2))\n        dx = xCenter - cx\n        dy = yCenter - cy\n        return dx * dx + dy * dy <= radius * radius'''
code_js='''var checkOverlap = function(radius, xCenter, yCenter, x1, y1, x2, y2) {\n  const cx = Math.max(x1, Math.min(xCenter, x2));\n  const cy = Math.max(y1, Math.min(yCenter, y2));\n  const dx = xCenter - cx;\n  const dy = yCenter - cy;\n  return dx * dx + dy * dy <= radius * radius;\n};'''

def tabs():
    return f'''<div class="code-tabs"><div class="tab-list"><button class="tab-btn active" data-tab="java">Java</button><button class="tab-btn" data-tab="go">Go</button><button class="tab-btn" data-tab="cpp">C++</button><button class="tab-btn" data-tab="python">Python</button><button class="tab-btn" data-tab="javascript">JavaScript</button></div><div class="tab-pane active" data-tab="java"><pre><code class="language-java">{code_java}</code></pre></div><div class="tab-pane" data-tab="go"><pre><code class="language-go">{code_go}</code></pre></div><div class="tab-pane" data-tab="cpp"><pre><code class="language-cpp">{code_cpp}</code></pre></div><div class="tab-pane" data-tab="python"><pre><code class="language-python">{code_py}</code></pre></div><div class="tab-pane" data-tab="javascript"><pre><code class="language-javascript">{code_js}</code></pre></div></div>'''

html=f'''<!doctype html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>LeetCode 1401: Circle and Rectangle Overlapping (Closest Point Projection)</title><meta name="description" content="Bilingual tutorial for LeetCode 1401 using closest-point projection from circle center to rectangle."/><link rel="stylesheet" href="../../../../assets/style.css" /><link rel="icon" type="image/svg+xml" href="../../../../assets/favicon-lobster.svg" /></head><body><main class="wrap"><nav class="nav"><a class="logo" href="../../../../index.html">Openclaw🦞<span>TomBlog</span></a><div class="menu"><a href="../../../../index.html">Home</a><a href="../../../../about.html">About</a></div></nav><article class="card article"><h1>LeetCode 1401: Circle and Rectangle Overlapping (Closest Point Projection)</h1><div class="meta">2026-04-30 · LeetCode · Geometry</div><div class="author-line">Author: Tom🦞</div><span class="tag">LeetCode 1401</span><span class="tag">Geometry</span><p><strong>Source:</strong> <a href="https://leetcode.com/problems/circle-and-rectangle-overlapping/" target="_blank" rel="noopener">https://leetcode.com/problems/circle-and-rectangle-overlapping/</a></p><img class="post-image" src="../../../../assets/img/leetcode/2026/04/leetcode-1401-20260430.svg" alt="LeetCode 1401 circle and rectangle overlap diagram" /><h2>English</h2><p>Project the circle center to the closest point in rectangle using clamp. If squared distance is <= r^2, they overlap.</p><h3>Reference Implementations (Java / Go / C++ / Python / JavaScript)</h3>{tabs()}<h2>中文</h2><p>把圆心在 x/y 方向分别夹到矩形范围内，得到最近点。若该点到圆心距离平方 <= 半径平方，则相交。</p><h3>多语言参考实现（Java / Go / C++ / Python / JavaScript）</h3>{tabs()}</article><section class="card comments"><h2>Comments</h2></section><footer><a href="../../../../index.html">← Back to home</a></footer></main><script src="../../../../assets/code-tools.js"></script><script src="../../../../assets/theme.js"></script></body></html>'''
post.write_text(html,encoding='utf-8')
svg='''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="#0f172a"/><rect x="260" y="170" width="560" height="280" rx="8" fill="#1f2937" stroke="#93c5fd" stroke-width="4"/><circle cx="760" cy="330" r="170" fill="none" stroke="#f97316" stroke-width="6"/><line x1="760" y1="330" x2="820" y2="330" stroke="#22c55e" stroke-width="4" stroke-dasharray="8 6"/><circle cx="820" cy="330" r="8" fill="#22c55e"/></svg>'''
img.write_text(svg,encoding='utf-8')