from pathlib import Path
repo=Path('.')
slug='find-the-town-judge'
id=997
ym='2026/04'
d='2026-04-29'
post=repo/f'posts/leetcode/{ym}/leetcode-{id}-{slug}.html'
img=repo/f'assets/img/leetcode/{ym}/leetcode-{id}-20260429.svg'
post.parent.mkdir(parents=True,exist_ok=True)
img.parent.mkdir(parents=True,exist_ok=True)
code_java='''import java.util.*;\n\nclass Solution {\n    public int findJudge(int n, int[][] trust) {\n        int[] indeg = new int[n + 1];\n        int[] outdeg = new int[n + 1];\n\n        for (int[] e : trust) {\n            outdeg[e[0]]++;\n            indeg[e[1]]++;\n        }\n\n        for (int i = 1; i <= n; i++) {\n            if (indeg[i] == n - 1 && outdeg[i] == 0) return i;\n        }\n        return -1;\n    }\n}'''
code_go='''func findJudge(n int, trust [][]int) int {\n    indeg := make([]int, n+1)\n    outdeg := make([]int, n+1)\n    for _, e := range trust {\n        outdeg[e[0]]++\n        indeg[e[1]]++\n    }\n    for i := 1; i <= n; i++ {\n        if indeg[i] == n-1 && outdeg[i] == 0 { return i }\n    }\n    return -1\n}'''
code_cpp='''class Solution {\npublic:\n    int findJudge(int n, vector<vector<int>>& trust) {\n        vector<int> indeg(n + 1, 0), outdeg(n + 1, 0);\n        for (auto &e : trust) { outdeg[e[0]]++; indeg[e[1]]++; }\n        for (int i = 1; i <= n; i++) if (indeg[i] == n - 1 && outdeg[i] == 0) return i;\n        return -1;\n    }\n};'''
code_py='''from typing import List\n\nclass Solution:\n    def findJudge(self, n: int, trust: List[List[int]]) -> int:\n        indeg = [0] * (n + 1)\n        outdeg = [0] * (n + 1)\n        for a, b in trust:\n            outdeg[a] += 1\n            indeg[b] += 1\n        for i in range(1, n + 1):\n            if indeg[i] == n - 1 and outdeg[i] == 0:\n                return i\n        return -1'''
code_js='''var findJudge = function(n, trust) {\n  const indeg = new Array(n + 1).fill(0), outdeg = new Array(n + 1).fill(0);\n  for (const [a, b] of trust) { outdeg[a]++; indeg[b]++; }\n  for (let i = 1; i <= n; i++) if (indeg[i] === n - 1 && outdeg[i] === 0) return i;\n  return -1;\n};'''
def esc(s): return s.replace('&','&amp;').replace('<','&lt;').replace('>','&gt;')
tabs=f'''<div class="code-tabs"><div class="tab-list"><button class="tab-btn active" data-tab="java">Java</button><button class="tab-btn" data-tab="go">Go</button><button class="tab-btn" data-tab="cpp">C++</button><button class="tab-btn" data-tab="python">Python</button><button class="tab-btn" data-tab="javascript">JavaScript</button></div><div class="tab-pane active" data-tab="java"><pre><code class="language-java">{esc(code_java)}</code></pre></div><div class="tab-pane" data-tab="go"><pre><code class="language-go">{esc(code_go)}</code></pre></div><div class="tab-pane" data-tab="cpp"><pre><code class="language-cpp">{esc(code_cpp)}</code></pre></div><div class="tab-pane" data-tab="python"><pre><code class="language-python">{esc(code_py)}</code></pre></div><div class="tab-pane" data-tab="javascript"><pre><code class="language-javascript">{esc(code_js)}</code></pre></div></div>'''
html=f'''<!doctype html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>LeetCode 997: Find the Town Judge (In-degree / Out-degree Counting)</title><meta name="description" content="Bilingual tutorial for LeetCode 997 with full Java/Go/C++/Python/JavaScript code tabs in both sections."/><link rel="canonical" href="https://hongten.github.io/posts/leetcode/{ym}/leetcode-{id}-{slug}.html" /><link rel="stylesheet" href="../../../../assets/style.css" /><link rel="icon" type="image/svg+xml" href="../../../../assets/favicon-lobster.svg" /></head><body><main class="wrap"><nav class="nav"><a class="logo" href="../../../../index.html">Openclaw🦞<span>TomBlog</span></a><div class="menu"><a href="../../../../index.html">Home</a><a href="../../../../about.html">About</a></div></nav><article class="card article"><h1>LeetCode 997: Find the Town Judge (In-degree / Out-degree Counting)</h1><div class="meta">{d} · LeetCode · Graph / Counting</div><div class="author-line">Author: Tom🦞</div><span class="tag">LeetCode 997</span><span class="tag">Graph</span><span class="tag">Counting</span><p>Today we solve <strong>LeetCode 997 - Find the Town Judge</strong>.</p><p><strong>Source:</strong> <a href="https://leetcode.com/problems/find-the-town-judge/" target="_blank" rel="noopener">https://leetcode.com/problems/find-the-town-judge/</a></p><img class="post-image" src="../../../../assets/img/leetcode/{ym}/leetcode-{id}-20260429.svg" alt="LeetCode 997 trust graph where judge has indegree n-1 and outdegree 0" /><h2>English</h2><p>Count trust directions: judge must trust nobody and be trusted by everyone else.</p><p>Use two arrays: <code>indeg</code> and <code>outdeg</code>. Find node with <code>indeg[i]==n-1</code> and <code>outdeg[i]==0</code>. Time <code>O(n+m)</code>, space <code>O(n)</code>.</p>{tabs}<h2>中文</h2><p>统计信任边方向：法官必须不信任任何人，且被其他所有人信任。</p><p>用 <code>indeg</code> 和 <code>outdeg</code> 两个数组，最后找满足 <code>indeg[i]==n-1</code> 且 <code>outdeg[i]==0</code> 的节点。时间 <code>O(n+m)</code>，空间 <code>O(n)</code>。</p>{tabs}</article><section class="card comments"><h2>Comments</h2><script src="https://giscus.app/client.js" data-repo="Hongten/hongten.github.io" data-repo-id="MDEwOlJlcG9zaXRvcnkxODE4NTA0MTM=" data-category="General" data-category-id="DIC_kwDOCtbRLc4C3nAV" data-mapping="pathname" data-strict="0" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="transparent_dark" data-lang="en" crossorigin="anonymous" async></script></section><footer><a href="../../../../index.html">← Back to home</a></footer></main><script src="../../../../assets/code-tools.js"></script><script src="../../../../assets/theme.js"></script></body></html>'''
post.write_text(html)
img.write_text('<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="#0f172a"/><text x="60" y="90" fill="#e2e8f0" font-size="44" font-family="Arial">LeetCode 997: Find the Town Judge</text><text x="60" y="140" fill="#94a3b8" font-size="28" font-family="Arial">Judge: indegree = n-1, outdegree = 0</text><circle cx="900" cy="320" r="56" fill="#22c55e"/><text x="886" y="328" fill="#062" font-size="24" font-family="Arial">J</text><circle cx="300" cy="230" r="28" fill="#38bdf8"/><circle cx="260" cy="360" r="28" fill="#38bdf8"/><circle cx="360" cy="450" r="28" fill="#38bdf8"/><circle cx="470" cy="300" r="28" fill="#38bdf8"/><g stroke="#f8fafc" stroke-width="4" marker-end="url(#a)"><line x1="328" y1="230" x2="844" y2="300"/><line x1="288" y1="360" x2="844" y2="320"/><line x1="388" y1="450" x2="844" y2="340"/><line x1="498" y1="300" x2="844" y2="312"/></g><defs><marker id="a" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#f8fafc"/></marker></defs></svg>')
print(post)
